.PHONY: train
train:
	python src/train.py --train-data /path/to/train/dataset --valid-data /path/to/valid/dataset

.PHONY: eval
	python src/eval.py --test-data /path/to/test/dataset --checkpoint /path/to/checkpoint/file
